msgbox "系统出现严重错误" 
msgbox"请重启电脑"
msgbox"10秒倒计时开始"
CreateObject("SAPI.SpVoice").Speak "10"
CreateObject("SAPI.SpVoice").Speak "9"
CreateObject("SAPI.SpVoice").Speak "8"
CreateObject("SAPI.SpVoice").Speak "7"
CreateObject("SAPI.SpVoice").Speak "6"
CreateObject("SAPI.SpVoice").Speak "5"
CreateObject("SAPI.SpVoice").Speak "4"
CreateObject("SAPI.SpVoice").Speak "3"
CreateObject("SAPI.SpVoice").Speak "2"
CreateObject("SAPI.SpVoice").Speak "1"
CreateObject("SAPI.SpVoice").Speak "恭喜您，您的电脑内部已经出现严重漏洞"